// Content data lives here so the workout catalog can grow without touching
// the planner's rendering and interaction logic.
window.WORKOUT_DATA = {
  exerciseLibrary: {
    chest: [
      { name: "Dumbbell floor press", equipment: ["dumbbells", "bodyweight"], sets: 3 },
      { name: "Dumbbell bench press", equipment: ["dumbbells"], requires: ["bench"], sets: 3 },
      { name: "Dumbbell bench fly", equipment: ["dumbbells"], requires: ["bench"], sets: 3 },
      { name: "Barbell bench press", equipment: ["barbell"], requires: ["bench"], setup: "barbell-bench", sets: 3 },
      { name: "EZ-bar bench press", equipment: ["ezbar"], requires: ["bench"], setup: "ezbar-bench", sets: 3 },
      { name: "Landmine chest press", equipment: ["landmine", "barbell"], requires: ["barbell"], setup: "landmine-standing", sets: 3 },
      { name: "Medicine ball chest pass", equipment: ["medicineball"], sets: 3 },
      { name: "Kettlebell floor press", equipment: ["kettlebells"], sets: 3 },
      { name: "Tube band chest press", equipment: ["tubebands"], sets: 3 },
      { name: "Bodyweight push-ups", equipment: ["bodyweight"], sets: 3 },
      { name: "Bodyweight bench incline push-ups", equipment: ["bodyweight", "bench"], sets: 3 },
    ],
    back: [
      { name: "Dumbbell row", equipment: ["dumbbells"], sets: 3 },
      { name: "Dumbbell bench-supported row", equipment: ["dumbbells"], requires: ["bench"], sets: 3 },
      { name: "Kettlebell row", equipment: ["kettlebells"], sets: 3 },
      { name: "Tube band row", equipment: ["tubebands"], sets: 3 },
      { name: "Pull-up bar pull-ups", equipment: ["pullupbar"], sets: 3 },
      { name: "Barbell bent-over row", equipment: ["barbell"], setup: "barbell-floor", sets: 3 },
      { name: "EZ-bar bent-over row", equipment: ["ezbar"], setup: "ezbar-floor", sets: 3 },
      { name: "Landmine row", equipment: ["landmine", "barbell"], requires: ["barbell"], setup: "landmine-floor", sets: 3 },
      { name: "Medicine ball pullover", equipment: ["medicineball"], requires: ["bench"], sets: 3 },
      { name: "Bodyweight prone Y-T raises", equipment: ["bodyweight", "bench"], sets: 2 },
      { name: "Bodyweight reverse snow angels", equipment: ["bodyweight"], sets: 2 },
    ],
    quads: [
      { name: "Dumbbell goblet squat", equipment: ["dumbbells"], sets: 3 },
      { name: "Dumbbell bench Bulgarian split squat", equipment: ["dumbbells", "bench"], sets: 3 },
      { name: "Kettlebell front squat", equipment: ["kettlebells"], sets: 3 },
      { name: "Barbell back squat", equipment: ["barbell"], requires: ["rack"], setup: "barbell-rack", sets: 3 },
      { name: "EZ-bar front squat", equipment: ["ezbar"], requires: ["rack"], setup: "ezbar-rack", sets: 3 },
      { name: "Landmine squat", equipment: ["landmine", "barbell"], requires: ["barbell"], setup: "landmine-standing", sets: 3 },
      { name: "Medicine ball goblet squat", equipment: ["medicineball"], sets: 3 },
      { name: "Tube band squat", equipment: ["tubebands"], sets: 3 },
      { name: "Tempo bodyweight squat", equipment: ["bodyweight"], sets: 3 },
      { name: "Bodyweight bench step-up", equipment: ["bodyweight", "bench"], sets: 3 },
    ],
    quadsCalves: [
      { name: "Dumbbell squat to calf raise", equipment: ["dumbbells"], sets: 3 },
      { name: "Kettlebell squat to calf raise", equipment: ["kettlebells"], sets: 3 },
      { name: "Tube band squat to calf raise", equipment: ["tubebands"], sets: 3 },
      { name: "Bodyweight squat to calf raise", equipment: ["bodyweight"], sets: 3 },
      { name: "Bodyweight step-up to calf raise", equipment: ["bodyweight", "bench"], sets: 3 },
      { name: "EZ-bar squat to calf raise", equipment: ["ezbar"], requires: ["rack"], setup: "ezbar-rack", sets: 3 },
      { name: "Landmine squat to calf raise", equipment: ["landmine", "barbell"], requires: ["barbell"], setup: "landmine-standing", sets: 3 },
      { name: "Medicine ball squat to calf raise", equipment: ["medicineball"], sets: 3 },
    ],
    hamstrings: [
      { name: "Dumbbell Romanian deadlift", equipment: ["dumbbells"], sets: 3 },
      { name: "Dumbbell single-leg RDL", equipment: ["dumbbells"], sets: 2 },
      { name: "Kettlebell deadlift", equipment: ["kettlebells"], sets: 3 },
      { name: "Barbell Romanian deadlift", equipment: ["barbell"], setup: "barbell-floor", sets: 3 },
      { name: "EZ-bar good morning", equipment: ["ezbar"], setup: "ezbar-standing", sets: 3 },
      { name: "Landmine Romanian deadlift", equipment: ["landmine", "barbell"], requires: ["barbell"], setup: "landmine-floor", sets: 3 },
      { name: "Medicine ball good morning", equipment: ["medicineball"], sets: 3 },
      { name: "Tube band good morning", equipment: ["tubebands"], sets: 3 },
      { name: "Bodyweight hamstring walkout", equipment: ["bodyweight"], sets: 2 },
      { name: "Bodyweight bench leg curl", equipment: ["bodyweight", "bench"], sets: 3 },
    ],
    core: [
      { name: "Bodyweight dead bug", equipment: ["bodyweight"], sets: 2 },
      { name: "Bodyweight plank shoulder tap", equipment: ["bodyweight"], sets: 2 },
      { name: "Dumbbell suitcase march", equipment: ["dumbbells"], sets: 2 },
      { name: "Kettlebell suitcase march", equipment: ["kettlebells"], sets: 2 },
      { name: "Tube band Pallof press", equipment: ["tubebands"], sets: 2 },
      { name: "Slam ball sit-up", equipment: ["slamball"], sets: 2 },
      { name: "Bodyweight bench knee tuck", equipment: ["bodyweight", "bench"], sets: 2 },
      { name: "Landmine rotation", equipment: ["landmine", "barbell"], requires: ["barbell"], setup: "landmine-standing", sets: 2 },
      { name: "Medicine ball Russian twist", equipment: ["medicineball"], sets: 2 },
      { name: "Medicine ball sit-up", equipment: ["medicineball"], sets: 2 },
    ],
    shoulders: [
      { name: "Dumbbell shoulder press", equipment: ["dumbbells"], sets: 3 },
      { name: "Dumbbell Arnold press", equipment: ["dumbbells"], sets: 3 },
      { name: "Kettlebell shoulder press", equipment: ["kettlebells"], sets: 3 },
      { name: "Barbell overhead press", equipment: ["barbell"], requires: ["rack"], setup: "barbell-rack", sets: 3 },
      { name: "EZ-bar overhead press", equipment: ["ezbar"], requires: ["rack"], setup: "ezbar-rack", sets: 3 },
      { name: "Landmine press", equipment: ["landmine", "barbell"], requires: ["barbell"], setup: "landmine-standing", sets: 3 },
      { name: "Medicine ball push press", equipment: ["medicineball"], sets: 3 },
      { name: "Tube band face pull", equipment: ["tubebands"], sets: 2 },
      { name: "Bodyweight pike push-up", equipment: ["bodyweight"], sets: 3 },
      { name: "Dumbbell lean-away lateral raise", equipment: ["dumbbells"], sets: 2 },
    ],
    biceps: [
      { name: "Dumbbell alternating curl", equipment: ["dumbbells"], sets: 2 },
      { name: "Dumbbell hammer curl", equipment: ["dumbbells"], sets: 2 },
      { name: "Kettlebell curl", equipment: ["kettlebells"], sets: 2 },
      { name: "Tube band curl", equipment: ["tubebands"], sets: 2 },
      { name: "Barbell curl", equipment: ["barbell"], setup: "barbell-standing", sets: 2 },
      { name: "EZ-bar curl", equipment: ["ezbar"], setup: "ezbar-standing", sets: 2 },
      { name: "Bodyweight plank to low push-up", equipment: ["bodyweight"], sets: 2 },
    ],
    triceps: [
      { name: "Dumbbell overhead triceps extension", equipment: ["dumbbells"], sets: 2 },
      { name: "Kettlebell triceps extension", equipment: ["kettlebells"], sets: 2 },
      { name: "Tube band pressdown", equipment: ["tubebands"], sets: 2 },
      { name: "Close-grip barbell press", equipment: ["barbell"], requires: ["bench"], setup: "barbell-bench", sets: 2 },
      { name: "EZ-bar lying triceps extension", equipment: ["ezbar"], requires: ["bench"], setup: "ezbar-bench", sets: 2 },
      { name: "Landmine close-grip press", equipment: ["landmine", "barbell"], requires: ["barbell"], setup: "landmine-standing", sets: 2 },
      { name: "Bodyweight close-grip push-up", equipment: ["bodyweight"], sets: 2 },
      { name: "Bodyweight bench triceps dip", equipment: ["bodyweight", "bench"], sets: 2 },
    ],
    glutes: [
      { name: "Dumbbell bench hip thrust", equipment: ["dumbbells", "bench"], sets: 3 },
      { name: "Kettlebell swing", equipment: ["kettlebells"], sets: 3 },
      { name: "Barbell bench hip thrust", equipment: ["barbell"], requires: ["bench"], setup: "barbell-bench", sets: 3 },
      { name: "EZ-bar bench hip thrust", equipment: ["ezbar"], requires: ["bench"], setup: "ezbar-bench", sets: 3 },
      { name: "Landmine reverse lunge", equipment: ["landmine", "barbell"], requires: ["barbell"], setup: "landmine-standing", sets: 3 },
      { name: "Medicine ball reverse lunge", equipment: ["medicineball"], sets: 3 },
      { name: "Tube band lateral walk", equipment: ["tubebands"], sets: 2 },
      { name: "Bodyweight single-leg glute bridge", equipment: ["bodyweight"], sets: 2 },
      { name: "Bodyweight reverse lunge", equipment: ["bodyweight"], sets: 3 },
      { name: "Dumbbell sumo squat", equipment: ["dumbbells"], sets: 3 },
    ],
  },

  warmupLibrary: {
    chest: [
      { name: "Bodyweight scapular push-up", equipment: ["bodyweight"], dose: "8 reps" },
      { name: "Bodyweight wall chest opener", equipment: ["bodyweight"], dose: "20 sec" },
      { name: "Tube band chest opener", equipment: ["tubebands"], dose: "12 reps" },
    ],
    back: [
      { name: "Tube band pull-apart", equipment: ["tubebands"], dose: "12 reps" },
      { name: "Scapular pull-up", equipment: ["pullupbar"], dose: "5 reps" },
      { name: "Bodyweight thread-the-needle", equipment: ["bodyweight"], dose: "6 / side" },
    ],
    quads: [
      { name: "Bodyweight squat", equipment: ["bodyweight"], dose: "10 reps" },
      { name: "Bodyweight half-kneeling hip flexor stretch", equipment: ["bodyweight"], dose: "20 sec / side" },
      { name: "Bodyweight reverse lunge", equipment: ["bodyweight"], dose: "6 / side" },
    ],
    quadsCalves: [
      { name: "Bodyweight squat to calf raise", equipment: ["bodyweight"], dose: "8 reps" },
      { name: "Bodyweight ankle rocks", equipment: ["bodyweight"], dose: "8 / side" },
      { name: "Bodyweight calf stretch + reach", equipment: ["bodyweight"], dose: "20 sec / side" },
    ],
    hamstrings: [
      { name: "Bodyweight hip hinge drill", equipment: ["bodyweight"], dose: "10 reps" },
      { name: "Bodyweight world's greatest stretch", equipment: ["bodyweight"], dose: "5 / side" },
      { name: "Tube band good morning", equipment: ["tubebands"], dose: "10 reps" },
    ],
    core: [
      { name: "Bodyweight dead bug", equipment: ["bodyweight"], dose: "6 / side" },
      { name: "Bodyweight bird dog", equipment: ["bodyweight"], dose: "6 / side" },
      { name: "Bodyweight open book rotation", equipment: ["bodyweight"], dose: "6 / side" },
    ],
    shoulders: [
      { name: "Bodyweight wall slide", equipment: ["bodyweight"], dose: "8 reps" },
      { name: "Bodyweight arm circles", equipment: ["bodyweight"], dose: "20 sec" },
      { name: "Tube band face pull", equipment: ["tubebands"], dose: "12 reps" },
    ],
    biceps: [
      { name: "Bodyweight arm swings", equipment: ["bodyweight"], dose: "20 sec" },
      { name: "Tube band row to reach", equipment: ["tubebands"], dose: "10 reps" },
      { name: "Bodyweight wrist and elbow circles", equipment: ["bodyweight"], dose: "20 sec" },
    ],
    triceps: [
      { name: "Bodyweight incline push-up", equipment: ["bodyweight", "bench"], dose: "8 reps" },
      { name: "Bodyweight overhead triceps stretch", equipment: ["bodyweight"], dose: "20 sec / side" },
      { name: "Tube band pressdown", equipment: ["tubebands"], dose: "10 reps" },
    ],
    glutes: [
      { name: "Bodyweight glute bridge", equipment: ["bodyweight"], dose: "10 reps" },
      { name: "Tube band lateral walk", equipment: ["tubebands"], dose: "8 / side" },
      { name: "Bodyweight hip airplane", equipment: ["bodyweight"], dose: "5 / side" },
    ],
  },

  universalWarmupSets: [
    [
      { name: "Bodyweight hip flexor stretch with reach", equipment: ["bodyweight"], dose: "20 sec / side" },
      { name: "Bodyweight open book rotation", equipment: ["bodyweight"], dose: "5 / side" },
      { name: "Bodyweight deep squat hold with breathing", equipment: ["bodyweight"], dose: "20–30 sec" },
    ],
    [
      { name: "Bodyweight calf stretch with reach", equipment: ["bodyweight"], dose: "20 sec / side" },
      { name: "Bodyweight thread-the-needle", equipment: ["bodyweight"], dose: "6 / side" },
      { name: "Bodyweight world's greatest stretch", equipment: ["bodyweight"], dose: "5 / side" },
    ],
    [
      { name: "Bodyweight 90/90 hip switch", equipment: ["bodyweight"], dose: "5 / side" },
      { name: "Bodyweight wall slide", equipment: ["bodyweight"], dose: "8 reps" },
      { name: "Bodyweight child's pose with side reach", equipment: ["bodyweight"], dose: "20 sec / side" },
    ],
    [
      { name: "Bodyweight hip airplane", equipment: ["bodyweight"], dose: "5 / side" },
      { name: "Bodyweight arm circles", equipment: ["bodyweight"], dose: "20 sec" },
      { name: "Bodyweight adductor rockback", equipment: ["bodyweight"], dose: "8 / side" },
    ],
  ],

  routineBlueprints: [
    { title: "Mixed strength", primaryMuscle: "hamstrings", muscles: ["hamstrings", "chest", "triceps", "shoulders", "core"] },
    { title: "Mixed strength", primaryMuscle: "quadsCalves", muscles: ["quadsCalves", "back", "glutes", "chest"] },
    { title: "Mixed strength", primaryMuscle: "hamstrings", muscles: ["biceps", "hamstrings", "shoulders", "triceps"] },
    { title: "Mixed strength", primaryMuscle: "quadsCalves", muscles: ["quadsCalves", "back", "glutes", "biceps", "core"] },
  ],

  primaryWarmupSets: ["W × 8 × 50%", "W × 4 × 75%"],
  primaryWorkingReps: "6–10",

  cardioOptions: [
    { name: "Steady incline walk", equipment: ["treadmill"] },
    { name: "Treadmill intervals", equipment: ["treadmill"] },
    { name: "Easy bike ride", equipment: ["bike"] },
    { name: "Stationary bike intervals", equipment: ["bike"] },
    { name: "Jump rope intervals", equipment: ["jumprope"] },
    { name: "Steady jump rope", equipment: ["jumprope"] },
    { name: "Easy rowing", equipment: ["rower"] },
    { name: "Rowing machine intervals", equipment: ["rower"] },
  ],
  defaultCardio: "Easy jog",
  cardioTiming: [
    { sets: "W", duration: "3 min" },
    { sets: "1", duration: "25 min" },
    { sets: "W", duration: "2 min" },
  ],
  equipmentLabels: {
    dumbbells: "Dumbbells",
    bench: "Adjustable bench",
    kettlebells: "Kettlebells",
    tubebands: "Tube bands",
    pullupbar: "Pull-up bar",
    barbell: "Olympic barbell + plates",
    ezbar: "EZ-bar",
    landmine: "Landmine extension",
    rack: "Adjustable rack",
    slamball: "Slam ball",
    medicineball: "Medicine ball",
    jumprope: "Jump rope",
    rower: "Rowing machine",
    treadmill: "Treadmill",
    bike: "Stationary bike",
  },
  muscleLabels: {
    quadsCalves: "quads + calves",
    fullBody: "full body",
  },
};
